"use client";

import React, { useState } from "react";
import { X, Copy, Check, FileDown, Printer, FileText } from "lucide-react";
import { FinalAnswer } from "@/types/consensus";

interface ExportModalProps {
  isOpen: boolean;
  onClose: () => void;
  answer: FinalAnswer;
}

export const ExportModal: React.FC<ExportModalProps> = ({ isOpen, onClose, answer }) => {
  const [copied, setCopied] = useState(false);

  if (!isOpen) return null;

  const generateMarkdown = () => {
    return `# ${answer.question}

> Mode: ${answer.mode.toUpperCase()} | Confidence: ${answer.confidence.level} (${Math.round(answer.confidence.score * 100)}%)
> Verified by Consensus AI on ${new Date(answer.createdAt).toLocaleString()}

## Answer
${answer.directAnswer}

## Why
${answer.whyExplanation}

## Evidence Summary
${answer.evidenceSummary}

## Verification Metrics
- Models Consulted: ${answer.modelsConsulted.map((m) => m.providerName).join(", ")}
- Extracted Claims: ${answer.claims.length}
- Disagreements Resolved: ${answer.disagreements.length}
- Anti-Hallucination Consistency Score: ${answer.consistencyCheck.antiHallucinationScore}/100

## Authoritative Sources
${
  answer.sources.length > 0
    ? answer.sources
        .map(
          (s, idx) =>
            `${idx + 1}. [${s.title}](${s.url}) - ${s.publisher} (${s.date || "Metadata unavailable"})`
        )
        .join("\n")
    : "No external sources referenced."
}

---
*Generated by Consensus AI: One question. Multiple AIs. One carefully verified answer.*
`;
  };

  const handleCopyMarkdown = () => {
    navigator.clipboard.writeText(generateMarkdown());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownloadMarkdown = () => {
    const md = generateMarkdown();
    const blob = new Blob([md], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `consensus-answer-${Date.now()}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleDownloadPlainText = () => {
    const text = `${answer.question}\n\nANSWER:\n${answer.directAnswer}\n\nWHY:\n${answer.whyExplanation}\n\nEVIDENCE:\n${answer.evidenceSummary}\n\nCONFIDENCE: ${answer.confidence.level}`;
    const blob = new Blob([text], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `consensus-answer-${Date.now()}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/75 backdrop-blur-sm p-4 animate-fade-in">
      <div className="w-full max-w-lg rounded-2xl border border-white/10 bg-[#0c1017] p-6 shadow-2xl overflow-hidden flex flex-col">
        {/* Header */}
        <div className="flex items-center justify-between border-b border-white/10 pb-4">
          <div className="flex items-center gap-2">
            <FileDown className="h-5 w-5 text-cyan-400" />
            <h3 className="text-base font-bold text-white">Export Verified Consensus</h3>
          </div>
          <button
            onClick={onClose}
            className="rounded-lg p-1 text-slate-400 hover:bg-white/5 hover:text-white"
          >
            <X className="h-5 w-5" />
          </button>
        </div>

        {/* Options */}
        <div className="py-5 space-y-2.5">
          <button
            onClick={handleCopyMarkdown}
            className="w-full flex items-center justify-between rounded-xl border border-white/5 bg-white/[0.02] p-3.5 hover:border-cyan-500/40 hover:bg-white/5 transition-all text-left"
          >
            <div className="flex items-center gap-3">
              <Copy className="h-4 w-4 text-cyan-400" />
              <div>
                <span className="text-xs font-bold text-white">Copy Markdown</span>
                <p className="text-[11px] text-slate-400">Formatted with citations and verification metrics</p>
              </div>
            </div>
            {copied ? (
              <span className="text-xs font-semibold text-emerald-400 flex items-center gap-1">
                <Check className="h-3.5 w-3.5" /> Copied
              </span>
            ) : (
              <span className="text-xs text-slate-400">Copy</span>
            )}
          </button>

          <button
            onClick={handleDownloadMarkdown}
            className="w-full flex items-center justify-between rounded-xl border border-white/5 bg-white/[0.02] p-3.5 hover:border-cyan-500/40 hover:bg-white/5 transition-all text-left"
          >
            <div className="flex items-center gap-3">
              <FileDown className="h-4 w-4 text-indigo-400" />
              <div>
                <span className="text-xs font-bold text-white">Download .md File</span>
                <p className="text-[11px] text-slate-400">Save Markdown report locally</p>
              </div>
            </div>
            <span className="text-xs text-slate-400">.md</span>
          </button>

          <button
            onClick={handleDownloadPlainText}
            className="w-full flex items-center justify-between rounded-xl border border-white/5 bg-white/[0.02] p-3.5 hover:border-cyan-500/40 hover:bg-white/5 transition-all text-left"
          >
            <div className="flex items-center gap-3">
              <FileText className="h-4 w-4 text-emerald-400" />
              <div>
                <span className="text-xs font-bold text-white">Download Plain Text</span>
                <p className="text-[11px] text-slate-400">Clean ASCII text summary</p>
              </div>
            </div>
            <span className="text-xs text-slate-400">.txt</span>
          </button>

          <button
            onClick={handlePrint}
            className="w-full flex items-center justify-between rounded-xl border border-white/5 bg-white/[0.02] p-3.5 hover:border-cyan-500/40 hover:bg-white/5 transition-all text-left"
          >
            <div className="flex items-center gap-3">
              <Printer className="h-4 w-4 text-amber-400" />
              <div>
                <span className="text-xs font-bold text-white">Print / Save as PDF</span>
                <p className="text-[11px] text-slate-400">Browser print dialog</p>
              </div>
            </div>
            <span className="text-xs text-slate-400">Print</span>
          </button>
        </div>

        {/* Footer */}
        <div className="border-t border-white/10 pt-4 flex justify-end">
          <button
            onClick={onClose}
            className="rounded-xl border border-white/10 bg-white/5 px-4 py-2 text-xs font-semibold text-slate-300 hover:bg-white/10"
          >
            Close
          </button>
        </div>
      </div>
    </div>
  );
};
