import { AnswerMode, FinalAnswer } from "@/types/consensus";

export interface DemoScenario {
  id: string;
  title: string;
  question: string;
  mode: AnswerMode;
  answer: FinalAnswer;
}

export const DEMO_SCENARIOS: DemoScenario[] = [
  {
    id: "demo-quantum",
    title: "Quantum Entanglement Verification",
    question: "Does quantum entanglement allow faster-than-light communication?",
    mode: "academic",
    answer: {
      id: "demo-ans-1",
      question: "Does quantum entanglement allow faster-than-light communication?",
      mode: "academic",
      analysis: {
        intent: "Physics inquiry regarding quantum information and special relativity constraints",
        domain: "physics",
        complexity: "high",
        requiresCurrentInformation: false,
        requiresSources: true,
        requiresCalculation: false,
        requiresCodeExecution: false,
        ambiguityDetected: false,
        riskLevel: "low",
      },
      directAnswer:
        "No. Quantum entanglement does not permit faster-than-light (FTL) communication or information transfer. Although measurement of one entangled particle instantaneously determines the quantum state of its counterpart, the measurement outcomes are fundamentally random, preventing either party from transmitting a deliberate message without a classical communication channel.",
      whyExplanation:
        "This boundary is formally proven by the No-Communication Theorem in quantum field theory. While quantum correlations exhibit non-local behavior (as experimentally confirmed by Clauser, Aspect, and Zeilinger, recipients of the 2022 Nobel Prize), extracting meaningful mutual information always requires comparing results through sub-light-speed classical signals.",
      evidenceSummary:
        "Unanimous convergence across 4 independent frontier models and confirmed by peer-reviewed quantum mechanical theorems. Zero conflicting empirical data exists.",
      claims: [
        {
          id: "claim-1",
          text: "Quantum entanglement does not permit faster-than-light information transfer.",
          category: "scientific",
          importance: "high",
          supportingModels: ["gemini", "openai", "anthropic", "deepseek"],
          contradictingModels: [],
          verificationStatus: "confirmed",
        },
        {
          id: "claim-2",
          text: "The No-Communication Theorem mathematically forbids signaling via shared entangled quantum states.",
          category: "definition",
          importance: "high",
          supportingModels: ["gemini", "openai", "anthropic", "deepseek"],
          contradictingModels: [],
          verificationStatus: "confirmed",
        },
        {
          id: "claim-3",
          text: "Alain Aspect, John Clauser, and Anton Zeilinger received the 2022 Nobel Prize in Physics for Bell inequality experiments.",
          category: "date",
          importance: "medium",
          supportingModels: ["gemini", "openai", "anthropic"],
          contradictingModels: [],
          verificationStatus: "confirmed",
          detectedValue: "2022",
        },
      ],
      verificationResults: [
        {
          claimId: "claim-1",
          verdict: "confirmed",
          evidence: [
            {
              id: "ev-1",
              sourceId: "src-prl",
              sourceTitle: "Physical Review Letters - No-Signaling Bounds",
              sourceUrl: "https://journals.aps.org/prl",
              snippet: "Local measurement operators commute with distant observables, preventing non-local modulation.",
              type: "peer_reviewed",
              confidenceWeight: 0.98,
            },
          ],
          reasoning: "Validated through established mathematical theorems in quantum electrodynamics.",
          confidence: 0.96,
        },
        {
          claimId: "claim-2",
          verdict: "confirmed",
          evidence: [
            {
              id: "ev-2",
              sourceId: "src-nature",
              sourceTitle: "Nature Physics - Quantum Foundations",
              sourceUrl: "https://www.nature.com/nphys",
              snippet: "Density matrices of local subsystems remain invariant under remote unitary operations.",
              type: "peer_reviewed",
              confidenceWeight: 0.97,
            },
          ],
          reasoning: "Corroborated across peer-reviewed physics literature.",
          confidence: 0.95,
        },
      ],
      disagreements: [],
      sources: [
        {
          id: "src-prl",
          title: "General Formulation of the No-Communication Theorem",
          publisher: "American Physical Society (APS)",
          url: "https://journals.aps.org/prl",
          date: "1998",
          sourceType: "academic_paper",
          supportsClaims: ["claim-1", "claim-2"],
          reliabilityScore: 0.98,
          reliabilityIndicator: "primary_peer_reviewed",
        },
        {
          id: "src-nobel",
          title: "The Nobel Prize in Physics 2022 - Advanced Information",
          publisher: "The Royal Swedish Academy of Sciences",
          url: "https://www.nobelprize.org/prizes/physics/2022/advanced-information",
          date: "2022-10-04",
          sourceType: "official_docs",
          supportsClaims: ["claim-3"],
          reliabilityScore: 0.99,
          reliabilityIndicator: "official_doc",
        },
      ],
      modelsConsulted: [
        { providerId: "gemini", providerName: "Google Gemini", model: "gemini-2.0-flash", status: "success", latencyMs: 420 },
        { providerId: "openai", providerName: "OpenAI GPT-4o", model: "gpt-4o", status: "success", latencyMs: 650 },
        { providerId: "anthropic", providerName: "Anthropic Claude 3.5", model: "claude-3-5-sonnet", status: "success", latencyMs: 580 },
        { providerId: "deepseek", providerName: "DeepSeek-V3", model: "deepseek-chat", status: "success", latencyMs: 710 },
      ],
      confidence: {
        level: "High",
        score: 0.95,
        rationale: "Unanimous consensus across 4 frontier models corroborated by primary peer-reviewed mathematical proofs.",
        agreementRatio: 1.0,
        unverifiedClaimsCount: 0,
        disagreementsResolved: 0,
      },
      consistencyCheck: {
        passed: true,
        checksPerformed: [
          "Question relevance verification",
          "Anti-hallucination evidence bounding",
          "Uncertainty preservation check",
          "Internal contradiction pass",
        ],
        antiHallucinationScore: 98,
        notes: ["Passed all consistency checks without hallucination."],
      },
      isDemo: true,
      createdAt: new Date().toISOString(),
    },
  },
  {
    id: "demo-disagreement",
    title: "Disagreement Detection: Tokyo Population",
    question: "What is the population of Tokyo?",
    mode: "balanced",
    answer: {
      id: "demo-ans-2",
      question: "What is the population of Tokyo?",
      mode: "balanced",
      analysis: {
        intent: "Demographic inquiry regarding municipal vs metropolitan population figures",
        domain: "general",
        complexity: "medium",
        requiresCurrentInformation: true,
        requiresSources: true,
        requiresCalculation: false,
        requiresCodeExecution: false,
        ambiguityDetected: false,
        riskLevel: "medium",
      },
      directAnswer:
        "The population of Tokyo depends strictly on boundary definition: the **Tokyo Metropolis (Prefecture)** has approximately **14.1 million** residents, whereas the broader **Greater Tokyo Metropolitan Area (Kanto Region)** encompasses approximately **37.4 million** people.",
      whyExplanation:
        "Consensus AI detected an active statistical disagreement among models. Several AI systems quoted 14 million while others stated 37 million. Rather than picking a majority vote, verification traced the divergence to administrative definitions: Tokyo-to (prefecture) vs the contiguous urban agglomeration defined by the UN Population Division.",
      evidenceSummary:
        "Clarified divergence between Tokyo Metropolitan Government statistics (14.09M as of 2024) and UN World Urbanization Prospects (37.4M). Both figures are correct within their respective definitions.",
      claims: [
        {
          id: "claim-tokyo-pref",
          text: "Tokyo Prefecture (Tokyo-to) has an administrative population of approximately 14.1 million residents.",
          category: "statistic",
          importance: "high",
          supportingModels: ["gemini", "anthropic"],
          contradictingModels: ["openai"],
          verificationStatus: "disputed",
          detectedValue: "14.1 million",
        },
        {
          id: "claim-tokyo-metro",
          text: "The Greater Tokyo Metropolitan Area contains approximately 37.4 million residents.",
          category: "statistic",
          importance: "high",
          supportingModels: ["openai", "deepseek"],
          contradictingModels: ["gemini"],
          verificationStatus: "disputed",
          detectedValue: "37.4 million",
        },
      ],
      verificationResults: [
        {
          claimId: "claim-tokyo-pref",
          verdict: "supported",
          evidence: [
            {
              id: "ev-tmg",
              sourceId: "src-tmg",
              sourceTitle: "Tokyo Metropolitan Government Official Census",
              sourceUrl: "https://www.metro.tokyo.lg.jp/english/about/history/history03.html",
              snippet: "Official registered resident count of Tokyo-to as of 2024 stands at 14,094,034.",
              type: "official_documentation",
              confidenceWeight: 0.95,
            },
          ],
          reasoning: "Verified against official Japanese prefecture municipal records.",
          confidence: 0.91,
        },
        {
          claimId: "claim-tokyo-metro",
          verdict: "supported",
          evidence: [
            {
              id: "ev-un",
              sourceId: "src-un",
              sourceTitle: "United Nations World Urbanization Prospects",
              sourceUrl: "https://population.un.org/wup/",
              snippet: "Tokyo agglomeration includes Kanagawa, Saitama, and Chiba prefectures.",
              type: "official_documentation",
              confidenceWeight: 0.94,
            },
          ],
          reasoning: "Verified as the standard United Nations urban agglomeration metric.",
          confidence: 0.92,
        },
      ],
      disagreements: [
        {
          id: "disagree-1",
          claimId: "claim-tokyo-pref",
          claimText: "Population figure for Tokyo",
          type: "number_mismatch",
          severity: "high",
          modelPositions: [
            { providerId: "gemini", providerName: "Google Gemini", position: "14.1 million (citing Tokyo-to prefecture)" },
            { providerId: "openai", providerName: "OpenAI GPT-4o", position: "37.4 million (citing Greater Tokyo Area)" },
            { providerId: "anthropic", providerName: "Anthropic Claude", position: "14.0 million (administrative city core)" },
            { providerId: "deepseek", providerName: "DeepSeek-V3", position: "37.2 million (urban agglomeration)" },
          ],
          resolutionStrategy: "Distinguish between administrative city limits (14.1M) and urban agglomeration (37.4M).",
          resolvedVerdict: "Both figures valid under differentiated boundary scopes.",
        },
      ],
      sources: [
        {
          id: "src-tmg",
          title: "Tokyo Population Statistics Overview",
          publisher: "Tokyo Metropolitan Government (TMG)",
          url: "https://www.metro.tokyo.lg.jp",
          date: "2024-01-01",
          sourceType: "government_dataset",
          supportsClaims: ["claim-tokyo-pref"],
          reliabilityScore: 0.96,
          reliabilityIndicator: "official_doc",
        },
        {
          id: "src-un",
          title: "World Urbanization Prospects: 2024 Revision",
          publisher: "United Nations Population Division",
          url: "https://population.un.org",
          date: "2024-06-15",
          sourceType: "government_dataset",
          supportsClaims: ["claim-tokyo-metro"],
          reliabilityScore: 0.95,
          reliabilityIndicator: "official_doc",
        },
      ],
      modelsConsulted: [
        { providerId: "gemini", providerName: "Google Gemini", model: "gemini-2.0-flash", status: "success", latencyMs: 390 },
        { providerId: "openai", providerName: "OpenAI GPT-4o", model: "gpt-4o", status: "success", latencyMs: 610 },
        { providerId: "anthropic", providerName: "Anthropic Claude 3.5", model: "claude-3-5-sonnet", status: "success", latencyMs: 520 },
        { providerId: "deepseek", providerName: "DeepSeek-V3", model: "deepseek-chat", status: "success", latencyMs: 680 },
      ],
      confidence: {
        level: "Moderate",
        score: 0.82,
        rationale: "Disagreement successfully disambiguated via primary government census data and UN definitions.",
        agreementRatio: 0.5,
        unverifiedClaimsCount: 0,
        disagreementsResolved: 1,
      },
      consistencyCheck: {
        passed: true,
        checksPerformed: [
          "Disagreement transparency validation",
          "Boundary condition verification",
          "Anti-hallucination evidence bounding",
        ],
        antiHallucinationScore: 94,
        notes: ["Preserved divergence and clearly noted definition scope difference."],
      },
      isDemo: true,
      createdAt: new Date().toISOString(),
    },
  },
  {
    id: "demo-math",
    title: "Deterministic Math: Algebraic Equation",
    question: "Solve the equation 4x - 8 = 24 and verify step-by-step.",
    mode: "math",
    answer: {
      id: "demo-ans-3",
      question: "Solve the equation 4x - 8 = 24 and verify step-by-step.",
      mode: "math",
      analysis: {
        intent: "Algebraic linear equation solving with deterministic verification",
        domain: "mathematics",
        complexity: "low",
        requiresCurrentInformation: false,
        requiresSources: false,
        requiresCalculation: true,
        requiresCodeExecution: false,
        ambiguityDetected: false,
        riskLevel: "low",
        detectedMathematicalExpressions: ["4x - 8 = 24"],
      },
      directAnswer: "The exact solution is **x = 8**.",
      whyExplanation:
        "Solving algebraically:\n1. Add 8 to both sides: `4x = 24 + 8 = 32`\n2. Divide both sides by 4: `x = 32 / 4 = 8`\n\nConsensus AI executed an isolated deterministic calculation engine to cross-verify the result independently from LLM text generation.",
      evidenceSummary:
        "Deterministically evaluated with mathjs symbolic parser: `x = 8`. Independent AI models (Gemini, OpenAI, DeepSeek) all matched the deterministic calculation.",
      claims: [
        {
          id: "claim-math-1",
          text: "The solution to 4x - 8 = 24 is x = 8.",
          category: "number",
          importance: "high",
          supportingModels: ["gemini", "openai", "deepseek"],
          contradictingModels: [],
          verificationStatus: "confirmed",
          detectedValue: 8,
        },
      ],
      verificationResults: [
        {
          claimId: "claim-math-1",
          verdict: "confirmed",
          evidence: [
            {
              id: "ev-math",
              snippet: "Deterministic mathjs parser calculated: x = 8",
              type: "deterministic_calculation",
              confidenceWeight: 0.99,
            },
          ],
          reasoning: "Deterministically verified by isolated algebraic solver.",
          confidence: 0.96,
        },
      ],
      disagreements: [],
      mathChecks: [
        {
          expression: "4x - 8 = 24",
          calculatedResult: "x = 8",
          modelResults: [
            { providerId: "gemini", providerName: "Google Gemini", extractedResult: 8, matchesCalculator: true },
            { providerId: "openai", providerName: "OpenAI GPT-4o", extractedResult: 8, matchesCalculator: true },
            { providerId: "deepseek", providerName: "DeepSeek-V3", extractedResult: 8, matchesCalculator: true },
          ],
          isIndependentlyVerified: true,
          explanation: "Solved linearly: 4x = 32 ➔ x = 8. Verified by deterministic engine.",
          discrepancies: [],
        },
      ],
      sources: [],
      modelsConsulted: [
        { providerId: "gemini", providerName: "Google Gemini", model: "gemini-2.0-flash", status: "success", latencyMs: 290 },
        { providerId: "openai", providerName: "OpenAI GPT-4o", model: "gpt-4o", status: "success", latencyMs: 440 },
        { providerId: "deepseek", providerName: "DeepSeek-V3", model: "deepseek-chat", status: "success", latencyMs: 380 },
      ],
      confidence: {
        level: "High",
        score: 0.96,
        rationale: "Deterministic calculation matches all AI model outputs.",
        agreementRatio: 1.0,
        unverifiedClaimsCount: 0,
        disagreementsResolved: 0,
      },
      consistencyCheck: {
        passed: true,
        checksPerformed: ["Deterministic algebraic equality check", "Arithmetic parity check"],
        antiHallucinationScore: 99,
        notes: ["Deterministic engine confirms model answers with zero error."],
      },
      isDemo: true,
      createdAt: new Date().toISOString(),
    },
  },
  {
    id: "demo-coding",
    title: "Coding Verification: Python vs Rust Memory Safety",
    question: "Compare Python and Rust memory management and explain how Rust prevents data races without a GC.",
    mode: "coding",
    answer: {
      id: "demo-ans-4",
      question: "Compare Python and Rust memory management and explain how Rust prevents data races without a GC.",
      mode: "coding",
      analysis: {
        intent: "Comparative systems programming and language runtime analysis",
        domain: "computer-science",
        complexity: "high",
        requiresCurrentInformation: false,
        requiresSources: true,
        requiresCalculation: false,
        requiresCodeExecution: true,
        ambiguityDetected: false,
        riskLevel: "low",
      },
      directAnswer:
        "Python relies on automatic Reference Counting paired with a cyclical Garbage Collector (GC) and the Global Interpreter Lock (GIL) in CPython, whereas Rust eliminates the garbage collector entirely by enforcing ownership, move semantics, and the Borrow Checker at compile time.",
      whyExplanation:
        "Rust prevents data races at compile-time via its core rule: at any given time, data may have either one mutable reference (`&mut T`) OR any number of immutable references (`&T`), but never both simultaneously across concurrent threads. The `Send` and `Sync` marker traits further guarantee thread safety statically.\n\nExecution Status: **Code reviewed but not executed.** Syntax verified against standard compiler rules.",
      evidenceSummary:
        "Validated across Anthropic Claude, OpenAI GPT-4o, and DeepSeek with official reference to the Rust Reference and Python 3.12 documentation.",
      claims: [
        {
          id: "claim-code-1",
          text: "Rust uses compile-time ownership and borrow checker rules instead of a runtime garbage collector.",
          category: "technical",
          importance: "high",
          supportingModels: ["anthropic", "openai", "deepseek"],
          contradictingModels: [],
          verificationStatus: "confirmed",
        },
        {
          id: "claim-code-2",
          text: "Python CPython runtime uses reference counting with a cyclic generational garbage collector.",
          category: "technical",
          importance: "high",
          supportingModels: ["anthropic", "openai", "deepseek"],
          contradictingModels: [],
          verificationStatus: "confirmed",
        },
      ],
      verificationResults: [
        {
          claimId: "claim-code-1",
          verdict: "confirmed",
          evidence: [
            {
              id: "ev-rust",
              sourceId: "src-rust-docs",
              sourceTitle: "The Rust Programming Language (Book) - Understanding Ownership",
              sourceUrl: "https://doc.rust-lang.org/book/ch04-00-understanding-ownership.html",
              snippet: "Ownership is Rust's most unique feature and has deep implications for the rest of the language.",
              type: "official_documentation",
              confidenceWeight: 0.98,
            },
          ],
          reasoning: "Verified against official Rust standard library specification.",
          confidence: 0.95,
        },
      ],
      codeChecks: [
        {
          code: `fn main() {\n    let mut data = vec![1, 2, 3];\n    let ref1 = &data;\n    // let ref2 = &mut data; // Compile error: cannot borrow as mutable\n    println!("{:?}", ref1);\n}`,
          language: "rust",
          syntaxValid: true,
          executed: false,
          reviewNotes: [
            "Rust borrow checker prevents simultaneous aliased mutation at compile time.",
            "Code reviewed but not executed.",
          ],
          statusReport: "Code reviewed but not executed.",
        },
      ],
      disagreements: [],
      sources: [
        {
          id: "src-rust-docs",
          title: "The Rust Reference - Memory Model and Aliasing",
          publisher: "The Rust Foundation",
          url: "https://doc.rust-lang.org/reference",
          date: "2024",
          sourceType: "official_docs",
          supportsClaims: ["claim-code-1"],
          reliabilityScore: 0.97,
          reliabilityIndicator: "official_doc",
        },
        {
          id: "src-python-docs",
          title: "Python 3 Internal Memory Management & Garbage Collection",
          publisher: "Python Software Foundation",
          url: "https://docs.python.org/3/c-api/memory.html",
          date: "2024",
          sourceType: "official_docs",
          supportsClaims: ["claim-code-2"],
          reliabilityScore: 0.96,
          reliabilityIndicator: "official_doc",
        },
      ],
      modelsConsulted: [
        { providerId: "anthropic", providerName: "Anthropic Claude 3.5", model: "claude-3-5-sonnet", status: "success", latencyMs: 610 },
        { providerId: "openai", providerName: "OpenAI GPT-4o", model: "gpt-4o", status: "success", latencyMs: 590 },
        { providerId: "deepseek", providerName: "DeepSeek-V3", model: "deepseek-chat", status: "success", latencyMs: 640 },
      ],
      confidence: {
        level: "High",
        score: 0.94,
        rationale: "Unanimous alignment between 3 coding frontier models corroborated by language official specifications.",
        agreementRatio: 1.0,
        unverifiedClaimsCount: 0,
        disagreementsResolved: 0,
      },
      consistencyCheck: {
        passed: true,
        checksPerformed: ["Code syntax validation", "Execution honesty reporting", "Reference verification"],
        antiHallucinationScore: 97,
        notes: ["Execution status honestly reported as 'Code reviewed but not executed'."],
      },
      isDemo: true,
      createdAt: new Date().toISOString(),
    },
  },
];
